### ISSUE TITLE
props dissapear when looking away

### ISSUE THREAD

**Issue by snowleopardd** [xesdoog/object-spawner#1]
i remember there was a way to make them permanent on the map, why not use that?, also would be cooler if we could spawn any prop by just typing the name

**Comment by xesdoog** [comment]
Hey there Mike,

Since this script is still in beta, objects are currently set to be automatically removed when you look or move away from them. You can disable this behavior yourself by following these simple steps:

  1. Open **object_spawner.lua** with a text editor like Notepad ++
  2. Go to line 120 or press CTRL + F and paste this `ENTITY.SET_ENTITY_AS_NO_LONGER_NEEDED(spawnedObject)`
  3. add "--" at the start of that line so it looks like this: `--ENTITY.SET_ENTITY_AS_NO_LONGER_NEEDED(spawnedObject)`
  4. Press CTRL + S to save.

> also would be cooler if we could spawn any prop by just typing the name

That is planned for the release version.
