### ISSUE TITLE
Feature Request: Save attached objects?

### ISSUE THREAD

**Issue by playfulwaffle** [xesdoog/object-spawner#5]
The option to attach objects to yourself is a really cool feature, and I can make some pretty good outfits with it, but would it be possible to implement some sort of feature that would let you save your currently attached objects?

That way, if you were to create an intricate costume out of attached objects, you could save it and apply it instantly later, instead of having to re-create it.

Is this feasible or am I just dreaming? I've seen people with other menus instantly apply props to themselves before.

**Comment by xesdoog** [comment]
Hello waffle,

> Is this feasible or am I just dreaming? I've seen people with other menus instantly apply props to themselves before.

No you're not dreaming. It's absolutely doable but if I end up adding it it will be in the improved version of Object Spawner that's implemented in [this script](https://github.com/YimMenu-Lua/Samurais-Scripts).
I know I shouldn't abandon older scripts but this new project makes creating, adding, removing features a lot easier, it has a solid config system which will allow the requested feature to be easily implemented instead of porting a whole config system just for that feature. *Also it has translation support lol*

I'll keep the issue open until I manage to find some time to add it.

**Comment by xesdoog** [comment]
@playfulwaffle
Your request was added to the improved version of Object Spawner that can be found here: 
[Samurai's Scripts](https://github.com/YimMenu-Lua/Samurais-Scripts) -> World tab -> Object Spawner

There's also a similar option for vehicles that can be found in the Vehicle tab -> Vehicle Creator
