### ISSUE TITLE
Feature: Custom tuning with objects

### ISSUE THREAD

**Issue by samueleul** [xesdoog/object-spawner#6]
Idk if it's possible but would be pretty cool if we could put like spoilers on cars that doesn't have spoilers, just attatching them, front bumpers, tuning stuff you know ? I tried to attach a object to somewhere that could look like a custom tuning, but the object kepts moving attached to the player.

**Comment by xesdoog** [comment]
Hello there!

Vehicle modkits are not spawnable objects so that wouldn't be possible unfortunately.
If you want to attach objects to your vehicle, consider trying the version [in this script](https://github.com/xesdoog/Samurais-Scripts). This is currently just a base but the object spawner in it is a little bit improved and allows you to attach objects to your vehicle.
